export const colorDescriptions: Record<string, string> = {
    AliceBlue: "A gossamer-light blend of white tea, cucumber water, and fresh linen, capturing the essence of morning frost on delicate petals.",
    AntiqueWhite: "A nostalgic composition of dried vanilla pods, aged parchment, and powdered iris root, evoking memories of vintage love letters.",
    Aqua: "A crystalline fusion of sea spray, frozen mint, and water lily, creating the sensation of diving into a pristine mountain lake.",
    Aquamarine: "A refreshing blend of sea salt, green melon, and fresh eucalyptus, reminiscent of ocean breezes on a summer morning.",
    Azure: "An ethereal combination of cloud mist, white sage, and clean ozone, capturing the essence of the sky after rain.",
    Beige: "A subtle harmony of blonde woods, creamy sandalwood, and soft suede, offering sophisticated neutrality.",
    Bisque: "A delicate blend of warm milk, toasted almonds, and vanilla cream, suggesting comfort and elegance.",
    Black: "An intense fusion of rare oud, black amber, and midnight jasmine, embodying ultimate mystery and power.",
    BlanchedAlmond: "A gentle mix of sweet almond milk, white honey, and fresh cream, creating a soft, nurturing embrace.",
    Blue: "A profound blend of deep ocean accord, arctic pine, and cool minerals, expressing infinite depth.",
    BlueViolet: "A mysterious combination of midnight orchid, wild blueberry, and incense smoke, suggesting royal opulence.",
    Brown: "A rich fusion of roasted coffee beans, aged leather, and tobacco leaf, offering warmth and sophistication.",
    BurlyWood: "A robust blend of cedar wood, raw honey, and weathered leather, evoking natural strength and character.",
    CadetBlue: "A disciplined mix of sea minerals, juniper berry, and crisp uniform linen, suggesting military precision.",
    Chartreuse: "An electric combination of fresh lime zest, young ginger, and spring leaves, creating vibrant energy.",
    Chocolate: "A decadent fusion of dark cacao, vanilla bourbon, and warm spices, embracing rich indulgence.",
    Coral: "A vibrant blend of blood orange, tropical flowers, and warm sand accord, capturing sunset on tropical shores.",
    CornflowerBlue: "A romantic mix of blue cornflower, morning dew, and fresh cotton, suggesting pastoral beauty.",
    Cornsilk: "A delicate harmony of fresh corn silk, sweet hay, and summer air, evoking sun-drenched farm fields.",
    Crimson: "A passionate blend of red roses, spiced berries, and dark musk, expressing intense desire.",
    Cyan: "A pure fusion of glacial water, frozen mint, and crystal accord, suggesting perfect clarity.",
    DarkBlue: "A profound mix of night-blooming water lily, deep sea accord, and black ink, expressing oceanic depths.",
    DarkCyan: "An mysterious blend of deep aquatic notes, dark seaweed, and cold stone, suggesting hidden depths.",
    DarkGoldenRod: "A rich combination of golden amber, toasted spices, and medieval honey wine, evoking ancient treasures.",
    DarkGray: "A sophisticated blend of silver musk, cool stone, and graphite accord, suggesting urban elegance.",
    DarkGreen: "An intense fusion of forest floor, crushed pine needles, and wet moss, capturing primeval woods.",
    DarkKhaki: "A rugged blend of dried herbs, sun-baked earth, and weathered canvas, suggesting adventure.",
    DarkMagenta: "A bewitching mix of black orchid, purple incense, and dark berries, expressing mysterious allure.",
    DarkOliveGreen: "An earthy combination of crushed olive leaves, vetiver root, and fresh herbs, evoking Mediterranean gardens.",
    DarkOrange: "An intense blend of bitter orange peel, warm amber, and exotic spices, suggesting tropical heat.",
    DarkOrchid: "A luxurious fusion of rare orchids, purple incense, and midnight rain, expressing exotic mystery.",
    DarkRed: "A powerful mix of black roses, dragon's blood incense, and dark woods, suggesting primal intensity.",
    DarkSalmon: "A gentle blend of pink grapefruit, coral flowers, and warm skin musk, evoking sunset warmth.",
    DarkSeaGreen: "A calming fusion of sea moss, green algae, and salt water, capturing ocean depths.",
    DarkSlateBlue: "A mysterious combination of night-blooming flowers, dark incense, and wet slate, suggesting hidden wisdom.",
    DarkSlateGray: "A profound blend of wet stone, dark moss, and mineral accord, evoking ancient foundations.",
    DarkTurquoise: "An intense mix of deep sea minerals, frozen aqua, and crystal musk, expressing ocean mysteries.",
    DarkViolet: "A seductive blend of purple flowers, dark berries, and midnight incense, suggesting royal mysteries.",
    DeepPink: "An intense fusion of hot pink pepper, electric rose, and vibrant musk, expressing bold femininity.",
    DeepSkyBlue: "A soaring blend of high altitude air, blue ozone, and crystal waters, capturing infinite skies.",
    DimGray: "A subtle mix of grey amber, smoke, and cool musk, suggesting understated elegance.",
    DodgerBlue: "An energetic combination of fresh air, blue water, and clean ozone, evoking summer sports.",
    FireBrick: "An intense blend of red clay, burning wood, and hot spices, suggesting architectural strength.",
    FloralWhite: "A delicate mix of white flowers, clean linen, and fresh air, expressing pure elegance.",
    ForestGreen: "A verdant fusion of pine needles, wild ferns, and forest air, capturing woodland depths.",
    Fuchsia: "An electric blend of exotic flowers, pink pepper, and sparkling aldehydes, expressing vivid energy.",
    Gainsboro: "A refined mix of silver musk, clean linen, and fresh air, suggesting quiet sophistication.",
    GhostWhite: "An ethereal blend of white musk, cold air, and translucent flowers, evoking spectral presence.",
    Gold: "A luxurious fusion of precious saffron, golden honey, and warm amber, expressing opulent wealth.",
    GoldenRod: "A warm blend of golden wheat, summer honey, and sun-warmed wood, suggesting harvest bounty.",
    Gray: "A balanced mix of silver sage, cool stone, and neutral musk, expressing perfect neutrality.",
    Green: "A vibrant fusion of fresh leaves, cut grass, and morning dew, capturing natural vitality.",
    GreenYellow: "An energetic blend of lime zest, young leaves, and morning air, suggesting spring awakening.",
    HoneyDew: "A sweet combination of fresh melon, morning dew, and cucumber water, evoking garden freshness.",
    HotPink: "An exuberant mix of pink pepper, electric rose, and bright berries, expressing playful energy.",
    IndianRed: "A rich blend of red clay, warm spices, and desert flowers, suggesting earthen warmth.",
    Indigo: "A profound fusion of night-blooming jasmine, dark ink, and deep musk, expressing mysterious depths.",
    Ivory: "A precious blend of white flowers, clean musk, and powdered vanilla, suggesting pure luxury.",
    Khaki: "A utilitarian mix of dried grass, warm canvas, and desert air, evoking military adventures.",
    Lavender: "A soothing blend of French lavender, soft powder, and white tea, offering gentle tranquility.",
    LavenderBlush: "A delicate fusion of pink lavender, rose petals, and soft powder, expressing romantic innocence.",
    LawnGreen: "A fresh blend of cut grass, morning dew, and clean air, capturing perfect summer mornings.",
    LemonChiffon: "A delicate mix of lemon zest, vanilla cream, and fresh air, suggesting light desserts.",
    LightBlue: "A gentle blend of sky mist, clean cotton, and fresh air, evoking spring mornings.",
    LightCoral: "A soft fusion of pink flowers, sea spray, and warm sand, suggesting tropical shores.",
    LightCyan: "A fresh combination of water lily, cool mint, and clean air, expressing aquatic clarity.",
    LightGoldenRodYellow: "A gentle mix of summer flowers, warm hay, and golden light, suggesting pastoral scenes.",
    LightGray: "A subtle blend of silver musk, clean linen, and morning air, expressing quiet elegance.",
    LightGreen: "A bright fusion of fresh leaves, sweet grass, and morning dew, capturing spring vitality.",
    LightPink: "A tender blend of rose petals, pink sugar, and soft musk, suggesting gentle romance.",
    LightSalmon: "A fresh mix of pink grapefruit, coral flowers, and sea spray, evoking coastal mornings.",
    LightSeaGreen: "A refreshing blend of sea minerals, green algae, and fresh water, suggesting tropical shores.",
    LightSkyBlue: "A bright combination of clean ozone, fresh air, and water mist, expressing open skies.",
    LightSlateGray: "A sophisticated mix of grey amber, cool stone, and clean musk, suggesting urban elegance.",
    LightSteelBlue: "A metallic blend of cool water, clean air, and silver musk, evoking industrial precision.",
    LightYellow: "A gentle fusion of lemon blossom, fresh air, and white musk, suggesting morning light.",
    Lime: "An intense blend of fresh lime zest, green leaves, and cool mint, expressing zesty energy.",
    LimeGreen: "A vibrant mix of lime peel, fresh herbs, and green leaves, suggesting tropical vitality.",
    Linen: "A clean blend of fresh cotton, warm air, and white flowers, evoking fresh laundry.",
    Magenta: "An electric fusion of exotic flowers, pink pepper, and bright berries, expressing bold energy.",
    Maroon: "A rich blend of aged wine, dark berries, and smoky wood, suggesting vintage luxury.",
    MediumAquaMarine: "A balanced mix of sea minerals, green algae, and fresh water, capturing ocean depths.",
    MediumBlue: "A deep blend of ocean water, arctic pine, and cool minerals, expressing maritime power.",
    MediumOrchid: "A luxurious mix of purple orchids, sweet berries, and exotic spices, suggesting tropical nights.",
    MediumPurple: "A royal blend of purple flowers, sweet incense, and dark musk, expressing mysterious allure.",
    MediumSeaGreen: "A fresh fusion of sea moss, green algae, and salt air, capturing coastal vitality.",
    MediumSlateBlue: "A mysterious mix of blue flowers, night air, and cool stone, suggesting twilight magic.",
    MediumSpringGreen: "A vibrant blend of fresh leaves, spring water, and young shoots, expressing new growth.",
    MediumTurquoise: "A fresh combination of sea minerals, aqua mist, and clean ozone, suggesting tropical waters.",
    MediumVioletRed: "A bold fusion of red violets, dark berries, and hot spices, expressing passionate intensity.",
    MidnightBlue: "A profound blend of night flowers, dark water, and cool air, capturing nocturnal mystery.",
    MintCream: "A fresh mix of sweet mint, cream, and clean air, suggesting cool desserts.",
    MistyRose: "A delicate blend of rose petals, morning mist, and soft powder, evoking romantic mornings.",
    Moccasin: "A warm fusion of leather, sweet suede, and desert flowers, suggesting Native American heritage.",
    NavajoWhite: "A earthy blend of desert sand, dry wood, and warm air, evoking southwestern landscapes.",
    Navy: "A disciplined mix of ocean depth, clean uniform, and cool air, suggesting military precision.",
    OldLace: "A vintage blend of antique fabric, dried flowers, and soft powder, expressing nostalgic elegance.",
    Olive: "A rich fusion of pressed olives, mediterranean herbs, and warm earth, capturing ancient groves.",
    OliveDrab: "A military blend of crushed leaves, canvas, and earth, suggesting camouflage in nature.",
    Orange: "A bright fusion of sweet orange, warm amber, and golden honey, expressing solar energy.",
    OrangeRed: "An intense blend of blood orange, hot spices, and warm amber, suggesting fiery heat.",
    Orchid: "A exotic mix of rare orchids, sweet vanilla, and tropical rain, expressing exotic beauty.",
    PaleGoldenRod: "A gentle blend of summer wheat, warm honey, and soft air, suggesting sunlit fields.",
    PaleGreen: "A soft fusion of young leaves, morning dew, and fresh air, expressing spring gentleness.",
    PaleTurquoise: "A delicate mix of sea spray, morning mist, and fresh water, suggesting coastal dawns.",
    PaleVioletRed: "A tender blend of pink roses, soft violet, and warm musk, evoking romantic twilight.",
    PapayaWhip: "A tropical fusion of ripe papaya, coconut cream, and warm vanilla, suggesting exotic desserts.",
    PeachPuff: "A soft blend of fresh peach skin, cream, and sweet powder, expressing gentle warmth.",
    Peru: "A rich mix of ancient wood, terra cotta, and wild vanilla, suggesting South American mysteries.",
    Pink: "A sweet blend of rose petals, cotton candy, and soft powder, expressing innocent joy.",
    Plum: "A rich fusion of ripe plums, purple flowers, and dark honey, suggesting opulent fruit.",
    PowderBlue: "A soft mix of clean linen, fresh air, and cool water, evoking pristine freshness.",
    Purple: "A royal blend of dark violets, black currant, and midnight incense, expressing majestic mystery.",
    RebeccaPurple: "A memorable fusion of purple flowers, night rain, and sweet memories, honoring Rebecca.",
    Red: "An intense blend of red roses, hot spices, and passionate musk, expressing pure energy.",
    RosyBrown: "A vintage mix of dried roses, old wood, and soft powder, suggesting antique elegance.",
    RoyalBlue: "A majestic blend of blue lotus, crown jewels, and noble incense, expressing regal power.",
    SaddleBrown: "A rich fusion of aged leather, polished wood, and tobacco, suggesting equestrian luxury.",
    Salmon: "A fresh blend of pink citrus, ocean spray, and warm sand, evoking coastal sunsets.",
    SandyBrown: "A warm mix of beach sand, coconut, and sun-warmed wood, suggesting tropical shores.",
    SeaGreen: "A fresh fusion of ocean flora, green algae, and salt spray, capturing maritime depths.",
    SeaShell: "A delicate blend of ocean shells, salt air, and warm sand, expressing beach memories.",
    Sienna: "An earthy mix of red clay, autumn leaves, and warm spices, suggesting Italian earth.",
    Silver: "A metallic blend of cool minerals, clean rain, and frost, expressing modern elegance.",
    SkyBlue: "A fresh fusion of clean ozone, morning air, and water mist, capturing open horizons.",
    SlateBlue: "A deep blend of blue flowers, wet stone, and cool mist, suggesting twilight mystery.",
    SlateGray: "A sophisticated mix of grey amber, rain-wet stone, and cool air, expressing urban refinement.",
    Snow: "A pure blend of frozen air, white musk, and clean cotton, suggesting winter freshness.",
    SpringGreen: "A vibrant fusion of young leaves, fresh grass, and morning dew, expressing new beginnings.",
    SteelBlue: "A metallic mix of cool water, industrial air, and clean metal, suggesting modern strength.",
    Tan: "A warm blend of beach sand, soft leather, and sun-warmed skin, evoking summer memories.",
    Teal: "A deep fusion of ocean minerals, dark seaweed, and cool mist, suggesting mysterious depths.",
    Thistle: "A wild blend of Scottish flowers, mountain air, and purple herbs, expressing untamed beauty.",
    Tomato: "A fresh mix of vine-ripened tomatoes, basil leaves, and Mediterranean herbs, suggesting garden harvest.",
    Turquoise: "A bright blend of ocean spray, tropical waters, and crystal minerals, expressing exotic shores.",
    Violet: "A sweet fusion of fresh violets, spring rain, and soft powder, suggesting delicate beauty.",
    Wheat: "A warm blend of golden grain, summer hay, and hot sun, evoking harvest fields.",
    White: "A pure fusion of white lily, clean cotton, and fresh snow, expressing absolute clarity.",
    WhiteSmoke: "A subtle mix of white musk, clean air, and soft incense, suggesting gentle mystery.",
    Yellow: "A bright blend of fresh citrus, golden sunshine, and clean air, expressing pure joy.",
    YellowGreen: "A fresh fusion of young leaves, spring pollen, and morning dew, suggesting new growth."
}
